[project]
name = "minesweeper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lihil[standard]>=0.2.20",
    "pytest>=8.4.1",
    "sqlalchemy>=2.0.41",
]
